import { ResourcePage, type ResourceField } from '../../components/common/ResourcePage';

const statusOptions = [{ value: 'ACTIVE', label: 'Hoạt động' }, { value: 'INACTIVE', label: 'Ngừng hoạt động' }];
export const CustomersPage = () => <ResourcePage endpoint="/customers" idField="customer_id" eyebrow="CRM" title="Quản lý khách hàng" description="Thông tin khách hàng phục vụ các dự án." entityName="Khách hàng" columns={[{ key: 'full_name', label: 'Họ tên', primary: true }, { key: 'phone', label: 'Số điện thoại' }, { key: 'email', label: 'Email' }, { key: 'address', label: 'Địa chỉ' }]} fields={[{ key: 'full_name', label: 'Họ tên', required: true }, { key: 'phone', label: 'Số điện thoại', type: 'tel' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'address', label: 'Địa chỉ' }, { key: 'note', label: 'Ghi chú', type: 'textarea' }]} />;
export const InvestorsPage = () => <ResourcePage endpoint="/investors" idField="investor_id" eyebrow="ĐỐI TÁC" title="Quản lý chủ đầu tư" description="Hồ sơ cá nhân hoặc tổ chức đầu tư dự án." entityName="Chủ đầu tư" columns={[{ key: 'organization', label: 'Tổ chức', primary: true }, { key: 'full_name', label: 'Người đại diện' }, { key: 'phone', label: 'Điện thoại' }, { key: 'email', label: 'Email' }]} fields={[{ key: 'full_name', label: 'Họ tên', required: true }, { key: 'organization', label: 'Tổ chức' }, { key: 'phone', label: 'Điện thoại', type: 'tel' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'address', label: 'Địa chỉ' }, { key: 'note', label: 'Ghi chú', type: 'textarea' }]} />;
export const EmployeesPage = () => <ResourcePage endpoint="/employees" idField="employee_id" eyebrow="NHÂN SỰ" title="Quản lý nhân sự" description="Danh sách nhân sự tham gia vận hành và dự án." entityName="Nhân sự" columns={[{ key: 'employee_code', label: 'Mã', primary: true }, { key: 'full_name', label: 'Họ tên' }, { key: 'position', label: 'Chức vụ' }, { key: 'department', label: 'Bộ phận' }, { key: 'phone', label: 'SĐT' }, { key: 'status', label: 'Trạng thái', format: 'status' }]} fields={[{ key: 'employee_code', label: 'Mã nhân viên', required: true }, { key: 'full_name', label: 'Họ tên', required: true }, { key: 'position', label: 'Chức vụ' }, { key: 'department', label: 'Bộ phận' }, { key: 'phone', label: 'Số điện thoại', type: 'tel' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'status', label: 'Trạng thái', type: 'select', options: statusOptions, required: true }]} />;
export const MaterialsPage = () => <ResourcePage endpoint="/materials" idField="material_id" eyebrow="KHO VẬT TƯ" title="Danh mục vật tư" description="Danh mục dùng để phân bổ vật tư theo dự án." entityName="Vật tư" columns={[{ key: 'material_code', label: 'Mã vật tư', primary: true }, { key: 'material_name', label: 'Tên vật tư' }, { key: 'unit', label: 'Đơn vị tính' }, { key: 'description', label: 'Mô tả' }]} fields={[{ key: 'material_code', label: 'Mã vật tư', required: true }, { key: 'material_name', label: 'Tên vật tư', required: true }, { key: 'unit', label: 'Đơn vị tính', required: true }, { key: 'description', label: 'Mô tả', type: 'textarea' }]} />;

const contractFields: ResourceField[] = [
  { key: 'contract_number', label: 'Số hợp đồng', required: true },
  { key: 'project_id', label: 'Dự án', type: 'select', required: true, source: { endpoint: '/projects?limit=100', valueKey: 'project_id', labelKey: 'project_name' } },
  { key: 'customer_id', label: 'Khách hàng', type: 'select', source: { endpoint: '/customers?limit=100', valueKey: 'customer_id', labelKey: 'full_name' } },
  { key: 'investor_id', label: 'Chủ đầu tư', type: 'select', source: { endpoint: '/investors?limit=100', valueKey: 'investor_id', labelKey: 'full_name', alternateLabelKey: 'organization' } },
  { key: 'signed_date', label: 'Ngày ký', type: 'date' }, { key: 'start_date', label: 'Ngày bắt đầu', type: 'date' }, { key: 'end_date', label: 'Ngày kết thúc', type: 'date' },
  { key: 'contract_value', label: 'Giá trị hợp đồng', type: 'number', required: true, min: 0, step: '1000000' },
  { key: 'status', label: 'Trạng thái', type: 'select', required: true, options: [{ value: 'DRAFT', label: 'Bản nháp' }, { value: 'SIGNED', label: 'Đã ký' }, { value: 'IN_PROGRESS', label: 'Đang thực hiện' }, { value: 'COMPLETED', label: 'Hoàn thành' }, { value: 'CANCELLED', label: 'Đã hủy' }] }, { key: 'note', label: 'Ghi chú', type: 'textarea' },
];
export const ContractsPage = () => <ResourcePage endpoint="/contracts" idField="contract_id" eyebrow="HỢP ĐỒNG" title="Quản lý hợp đồng" description="Giá trị và trạng thái hợp đồng theo dự án." entityName="Hợp đồng" columns={[{ key: 'contract_number', label: 'Số hợp đồng', primary: true }, { key: 'project_name', label: 'Dự án' }, { key: 'customer_name', label: 'Khách hàng' }, { key: 'signed_date', label: 'Ngày ký', format: 'date' }, { key: 'contract_value', label: 'Giá trị', format: 'currency' }, { key: 'status', label: 'Trạng thái', format: 'status' }]} fields={contractFields} beforeSubmit={(data) => ({ ...data, project_id: Number(data.project_id), customer_id: data.customer_id ? Number(data.customer_id) : null, investor_id: data.investor_id ? Number(data.investor_id) : null })} />;

const userFields: ResourceField[] = [
  { key: 'username', label: 'Tên đăng nhập', required: true, createOnly: true }, { key: 'password', label: 'Mật khẩu', required: true, createOnly: true },
  { key: 'full_name', label: 'Họ tên', required: true }, { key: 'email', label: 'Email', type: 'email' }, { key: 'phone', label: 'Số điện thoại', type: 'tel' },
  { key: 'employee_id', label: 'Hồ sơ nhân sự', type: 'select', source: { endpoint: '/employees?limit=100', valueKey: 'employee_id', labelKey: 'full_name' } },
  { key: 'role_id', label: 'Vai trò', type: 'select', required: true, source: { endpoint: '/roles?limit=100', valueKey: 'role_id', labelKey: 'role_name' } },
  { key: 'status', label: 'Trạng thái', type: 'select', required: true, options: [{ value: 'ACTIVE', label: 'Hoạt động' }, { value: 'LOCKED', label: 'Đã khóa' }] },
];
export const UsersPage = () => <ResourcePage endpoint="/users" idField="user_id" eyebrow="BẢO MẬT" title="Quản lý người dùng" description="Tạo tài khoản, gán vai trò, khóa và đặt lại mật khẩu." entityName="Người dùng" passwordReset columns={[{ key: 'username', label: 'Tên đăng nhập', primary: true }, { key: 'full_name', label: 'Họ tên' }, { key: 'email', label: 'Email' }, { key: 'role_name', label: 'Vai trò' }, { key: 'status', label: 'Trạng thái', format: 'status' }, { key: 'created_at', label: 'Ngày tạo', format: 'date' }]} fields={userFields} beforeSubmit={(data) => ({ ...data, role_id: Number(data.role_id), employee_id: data.employee_id ? Number(data.employee_id) : null })} />;
