import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Eye, KeyRound, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { api, getApiError } from '../../api/client';
import { useToast } from '../../contexts/ToastContext';
import type { ApiResponse, Pagination as PaginationType } from '../../types';
import { formatCurrency, formatDate, formatStatus } from '../../utils/format';
import { EmptyState, ErrorState, LoadingState } from './Feedback';
import { ConfirmModal, Modal } from './Modal';
import { PageHeader } from './PageHeader';
import { Pagination } from './Pagination';
import { StatusBadge } from './StatusBadge';

export interface ResourceColumn { key: string; label: string; format?: 'date' | 'currency' | 'status'; primary?: boolean }
export interface ResourceField {
  key: string; label: string; type?: 'text' | 'email' | 'tel' | 'textarea' | 'number' | 'date' | 'select';
  required?: boolean; createOnly?: boolean; options?: Array<{ value: string | number; label: string }>;
  source?: { endpoint: string; valueKey: string; labelKey: string; alternateLabelKey?: string };
  min?: number; max?: number; step?: string;
}
interface Props { endpoint: string; idField: string; eyebrow: string; title: string; description: string; entityName: string; columns: ResourceColumn[]; fields: ResourceField[]; passwordReset?: boolean; beforeSubmit?: (data: Record<string, unknown>) => Record<string, unknown> }
const defaultPagination: PaginationType = { page: 1, limit: 10, total: 0, totalPages: 1 };

export function ResourcePage({ endpoint, idField, eyebrow, title, description, entityName, columns, fields, passwordReset, beforeSubmit }: Props) {
  const { showToast } = useToast(); const [items, setItems] = useState<Record<string, unknown>[]>([]); const [pagination, setPagination] = useState(defaultPagination); const [search, setSearch] = useState(''); const [draftSearch, setDraftSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<Record<string, unknown> | null>(null); const [viewing, setViewing] = useState<Record<string, unknown> | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<Record<string, unknown>>({}); const [options, setOptions] = useState<Record<string, Array<{ value: string | number; label: string }>>>({}); const [remove, setRemove] = useState<Record<string, unknown> | null>(null); const [saving, setSaving] = useState(false); const [resetUser, setResetUser] = useState<Record<string, unknown> | null>(null); const [newPassword, setNewPassword] = useState('');
  async function load(page = 1) { setLoading(true); setError(''); try { const response = await api.get<ApiResponse<Record<string, unknown>[]>>(endpoint, { params: { page, limit: 10, search } }); setItems(response.data.data); setPagination(response.data.pagination || defaultPagination); } catch (err) { setError(getApiError(err)); } finally { setLoading(false); } }
  useEffect(() => { void load(1); }, [search, endpoint]);
  async function openForm(item?: Record<string, unknown>) { setEditing(item || null); setForm(item ? { ...item } : {}); setFormOpen(true); const sourced = fields.filter((field) => field.source); try { const entries = await Promise.all(sourced.map(async (field) => { const source = field.source!; const response = await api.get<ApiResponse<Record<string, unknown>[]>>(source.endpoint); return [field.key, response.data.data.map((option) => ({ value: option[source.valueKey] as string | number, label: String(option[source.alternateLabelKey || ''] || option[source.labelKey]) }))] as const; })); setOptions(Object.fromEntries(entries)); } catch (err) { showToast(getApiError(err), 'error'); } }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { const payload = beforeSubmit ? beforeSubmit(form) : form; if (editing) await api.put(`${endpoint}/${editing[idField]}`, payload); else await api.post(endpoint, payload); showToast(editing ? 'Cập nhật thành công.' : 'Thêm thành công.'); setFormOpen(false); await load(pagination.page); } catch (err) { showToast(getApiError(err), 'error'); } finally { setSaving(false); } }
  async function confirmDelete() { if (!remove) return; setSaving(true); try { await api.delete(`${endpoint}/${remove[idField]}`); showToast('Xóa thành công.'); setRemove(null); await load(pagination.page); } catch (err) { showToast(getApiError(err), 'error'); } finally { setSaving(false); } }
  async function submitReset(event: FormEvent) { event.preventDefault(); if (!resetUser) return; setSaving(true); try { await api.patch(`${endpoint}/${resetUser[idField]}/reset-password`, { password: newPassword }); showToast('Đặt lại mật khẩu thành công.'); setResetUser(null); setNewPassword(''); } catch (err) { showToast(getApiError(err), 'error'); } finally { setSaving(false); } }
  function renderValue(item: Record<string, unknown>, column: ResourceColumn): ReactNode { const value = item[column.key]; if (column.format === 'status') return <StatusBadge status={String(value || '')} />; if (column.format === 'date') return formatDate(String(value || '')); if (column.format === 'currency') return <strong>{formatCurrency(Number(value))}</strong>; return String(value ?? '—'); }
  return (
    <>
      <PageHeader eyebrow={eyebrow} title={title} description={description} actions={<button className="button button--accent" onClick={() => openForm()}><Plus /> Thêm mới</button>} />
      <section className="panel table-panel"><form className="table-toolbar" onSubmit={(event) => { event.preventDefault(); setSearch(draftSearch); }}><label className="search-box"><Search /><input value={draftSearch} onChange={(e) => setDraftSearch(e.target.value)} placeholder={`Tìm kiếm ${entityName.toLowerCase()}...`} /></label><button className="button button--secondary">Tìm kiếm</button></form>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={() => load(pagination.page)} /> : !items.length ? <EmptyState title={`Chưa có ${entityName.toLowerCase()}`} /> : <><div className="table-scroll"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}<th className="actions-cell">Thao tác</th></tr></thead><tbody>{items.map((item) => <tr key={String(item[idField])}>{columns.map((column) => <td key={column.key} className={column.primary ? 'table-primary-cell' : ''}>{renderValue(item, column)}</td>)}<td className="actions-cell"><button className="icon-button" title="Xem" onClick={() => setViewing(item)}><Eye /></button><button className="icon-button" title="Sửa" onClick={() => openForm(item)}><Pencil /></button>{passwordReset && <button className="icon-button" title="Đặt lại mật khẩu" onClick={() => setResetUser(item)}><KeyRound /></button>}<button className="icon-button icon-button--danger" title="Xóa" onClick={() => setRemove(item)}><Trash2 /></button></td></tr>)}</tbody></table></div><Pagination pagination={pagination} onPageChange={load} /></>}</section>
      <Modal open={formOpen} title={editing ? `Cập nhật ${entityName.toLowerCase()}` : `Thêm ${entityName.toLowerCase()}`} onClose={() => setFormOpen(false)} size="large"><form className="modal-form resource-form" onSubmit={submit}><div className="form-grid">{fields.filter((field) => !(editing && field.createOnly)).map((field) => <label key={field.key} className={field.type === 'textarea' ? 'full' : ''}>{field.label}{field.required ? ' *' : ''}{field.type === 'textarea' ? <textarea required={field.required} rows={4} value={String(form[field.key] ?? '')} onChange={(e) => setForm({ ...form, [field.key]: e.target.value })} /> : field.type === 'select' ? <select required={field.required} value={String(form[field.key] ?? '')} onChange={(e) => setForm({ ...form, [field.key]: e.target.value })}><option value="">Chọn {field.label.toLowerCase()}</option>{(field.options || options[field.key] || []).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input required={field.required} type={field.createOnly ? 'password' : field.type || 'text'} min={field.min} max={field.max} step={field.step} value={String(form[field.key] ?? '')} onChange={(e) => setForm({ ...form, [field.key]: field.type === 'number' ? Number(e.target.value) : e.target.value })} />}</label>)}</div><footer className="modal-actions"><button type="button" className="button button--ghost" onClick={() => setFormOpen(false)}>Hủy</button><button className="button button--accent" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu dữ liệu'}</button></footer></form></Modal>
      <Modal open={Boolean(viewing)} title={`Chi tiết ${entityName.toLowerCase()}`} onClose={() => setViewing(null)}><dl className="resource-detail">{viewing && fields.filter((field) => !field.createOnly).map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{field.type === 'select' && field.options ? formatStatus(String(viewing[field.key] || '')) : String(viewing[field.key] ?? '—')}</dd></div>)}</dl></Modal>
      <ConfirmModal open={Boolean(remove)} busy={saving} message={`Bạn có chắc chắn muốn xóa ${entityName.toLowerCase()} này?`} onClose={() => setRemove(null)} onConfirm={confirmDelete} />
      <Modal open={Boolean(resetUser)} title="Đặt lại mật khẩu" onClose={() => setResetUser(null)}><form className="modal-form" onSubmit={submitReset}><p>Tạo mật khẩu mới cho tài khoản <strong>{String(resetUser?.username || '')}</strong>.</p><label>Mật khẩu mới *<input required minLength={8} type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><footer className="modal-actions"><button type="button" className="button button--ghost" onClick={() => setResetUser(null)}>Hủy</button><button className="button button--accent" disabled={saving}>Đặt lại mật khẩu</button></footer></form></Modal>
    </>
  );
}
