import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Download, FileImage, FileText, ImagePlus, Trash2, UploadCloud } from 'lucide-react';
import { api, getApiError, SERVER_BASE_URL } from '../../api/client';
import { useToast } from '../../contexts/ToastContext';
import type { ApiResponse } from '../../types';
import { formatDate, formatNumber } from '../../utils/format';
import { EmptyState, ErrorState, LoadingState } from './Feedback';
import { ConfirmModal } from './Modal';

interface ProjectFile { file_id: number; original_name: string; file_path: string; file_type: string; mime_type: string; file_size: number; uploaded_by_name: string; uploaded_at: string }
interface ProjectImage { image_id: number; title: string; description?: string; image_path: string; uploaded_by_name: string; uploaded_at: string }

const fileUrl = (path: string) => `${SERVER_BASE_URL}/${path.replace(/^\//, '')}`;

export function ProjectFilesTab({ projectId, mode, canDelete }: { projectId: number; mode: 'files' | 'images'; canDelete: boolean }) {
  const { showToast } = useToast(); const inputRef = useRef<HTMLInputElement>(null); const [files, setFiles] = useState<ProjectFile[]>([]); const [images, setImages] = useState<ProjectImage[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [uploading, setUploading] = useState(false); const [remove, setRemove] = useState<{ id: number; name: string } | null>(null); const [title, setTitle] = useState(''); const [description, setDescription] = useState('');
  async function load() { setLoading(true); try { if (mode === 'files') { const response = await api.get<ApiResponse<ProjectFile[]>>(`/projects/${projectId}/files`); setFiles(response.data.data); } else { const response = await api.get<ApiResponse<ProjectImage[]>>(`/projects/${projectId}/images`); setImages(response.data.data); } setError(''); } catch (err) { setError(getApiError(err)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [projectId, mode]);
  async function upload(event: FormEvent) { event.preventDefault(); const selected = inputRef.current?.files; if (!selected?.length) { showToast('Vui lòng chọn tệp cần upload.', 'error'); return; } setUploading(true); try { const data = new FormData(); if (mode === 'files') { data.append('file', selected[0]); data.append('file_type', 'DRAWING'); await api.post(`/projects/${projectId}/files`, data, { headers: { 'Content-Type': 'multipart/form-data' } }); } else { Array.from(selected).forEach((file) => data.append('images', file)); data.append('title', title); data.append('description', description); await api.post(`/projects/${projectId}/images`, data, { headers: { 'Content-Type': 'multipart/form-data' } }); } showToast('Upload thành công.'); if (inputRef.current) inputRef.current.value = ''; setTitle(''); setDescription(''); await load(); } catch (err) { showToast(getApiError(err), 'error'); } finally { setUploading(false); } }
  async function confirmRemove() { if (!remove) return; try { await api.delete(`/${mode === 'files' ? 'files' : 'images'}/${remove.id}`); showToast('Xóa thành công.'); setRemove(null); await load(); } catch (err) { showToast(getApiError(err), 'error'); } }
  return (
    <div className="files-tab"><form className="upload-panel" onSubmit={upload}><div className="upload-icon">{mode === 'files' ? <UploadCloud /> : <ImagePlus />}</div><div><h2>{mode === 'files' ? 'Upload bản vẽ / tài liệu' : 'Upload hình ảnh công trình'}</h2><p>{mode === 'files' ? 'Chấp nhận PDF, JPG, JPEG, PNG. Dung lượng tối đa 10 MB.' : 'Chọn tối đa 10 ảnh JPG, JPEG hoặc PNG mỗi lần.'}</p></div>{mode === 'images' && <div className="upload-meta"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Tiêu đề bộ ảnh" /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Mô tả ngắn" /></div>}<label className="file-picker"><input ref={inputRef} type="file" multiple={mode === 'images'} accept={mode === 'files' ? '.pdf,.jpg,.jpeg,.png' : '.jpg,.jpeg,.png'} /><span>Chọn {mode === 'files' ? 'tệp' : 'hình ảnh'}</span></label><button className="button button--accent" disabled={uploading}>{uploading ? 'Đang upload...' : 'Upload'}</button></form>
      <section className="panel table-panel"><header className="panel-table-header"><div><span className="panel-kicker">{mode === 'files' ? 'HỒ SƠ DỰ ÁN' : 'GALLERY CÔNG TRÌNH'}</span><h2>{mode === 'files' ? 'Bản vẽ & tài liệu' : 'Hình ảnh đã upload'}</h2></div></header>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : mode === 'files' ? (!files.length ? <EmptyState title="Chưa có bản vẽ hoặc tài liệu" /> : <div className="file-list">{files.map((file) => <article key={file.file_id}><FileText /><div><strong>{file.original_name}</strong><span>{file.uploaded_by_name} · {formatDate(file.uploaded_at)} · {formatNumber(Math.ceil(file.file_size / 1024))} KB</span></div><a className="icon-button" href={fileUrl(file.file_path)} target="_blank" rel="noreferrer"><Download /></a>{canDelete && <button className="icon-button icon-button--danger" onClick={() => setRemove({ id: file.file_id, name: file.original_name })}><Trash2 /></button>}</article>)}</div>) : (!images.length ? <EmptyState title="Chưa có hình ảnh công trình" /> : <div className="admin-gallery">{images.map((image) => <figure key={image.image_id}><div><img src={fileUrl(image.image_path)} alt={image.title || 'Hình ảnh công trình'} />{canDelete && <button className="icon-button icon-button--danger" onClick={() => setRemove({ id: image.image_id, name: image.title })}><Trash2 /></button>}</div><figcaption><FileImage /><div><strong>{image.title}</strong><span>{image.description || formatDate(image.uploaded_at)}</span></div></figcaption></figure>)}</div>)}</section>
      <ConfirmModal open={Boolean(remove)} message={`Bạn có chắc chắn muốn xóa “${remove?.name}”? Tệp lưu trên máy cũng sẽ bị xóa.`} onClose={() => setRemove(null)} onConfirm={confirmRemove} />
    </div>
  );
}
